/*
 * File: app/view/MyForm.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Import.view.MyForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    height: 280,
    width: 519,
    layout: 'absolute',
    bodyPadding: 10,
    title: '导入',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 50,
                    y: 20,
                    width: 350,
                    fieldLabel: '导入功能',
                    name: 'module',
                    value: 1,
                    editable: false,
                    store: 'MyStore',
                    valueField: 'id',
                    listeners: {
                        change: {
                            fn: me.onComboboxChange,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'combobox',
                    x: 50,
                    y: 70,
                    width: 350,
                    fieldLabel: '功能类型',
                    name: 'mType',
                    value: 11,
                    editable: false,
                    store: 'MyStore1',
                    valueField: 'id'
                },
                {
                    xtype: 'filefield',
                    x: 50,
                    y: 120,
                    fieldLabel: '选择文件',
                    name: 'file',
                    allowBlank: false,
                    buttonText: '选择文件'
                },
                {
                    xtype: 'button',
                    x: 400,
                    y: 170,
                    text: '确认导入',
                    listeners: {
                        click: {
                            fn: me.onButtonClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        var m = field.getStore().getById(newValue);
        var mType = this.down('[name=mType]');
        var s = mType.getStore();
        s.loadData(m.raw.children);
        mType.setValue(m.raw.children[0].id);
    },

    onButtonClick: function(button, e, eOpts) {
        if(this.down('filefield').getValue()=='' || this.down('filefield').getValue()==null){
            alert('请选择文件');
        }else{
            this.submit({
                url:'excel/parse',
                success:function(form,rs){
                    var resText = Ext.JSON.decode(rs.response.responseText).data;
                    resText = Ext.JSON.decode(resText);
                    window.parent.postMessage(resText,'http://112.111.2.107');
                }
            });
        }
    }

});