/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Import.store.MyStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyStore',
            data: [
                {
                    id: 1,
                    text: '思想品德管理',
                    children: [
                        {
                            id: 11,
                            text: '活动项目'
                        },
                        {
                            id: 12,
                            text: '先进个人荣誉项目'
                        },
                        {
                            id: 13,
                            text: '违纪违规项目'
                        }
                    ]
                },
                {
                    id: 3,
                    text: '身心健康管理',
                    children: [
                        {
                            id: 31,
                            text: '参加体育比赛项目'
                        },
                        {
                            id: 32,
                            text: '运动员国家技术等级'
                        }
                    ]
                },
                {
                    id: 4,
                    text: '艺术素养管理',
                    children: [
                        {
                            id: 41,
                            text: '参加艺术活动项目'
                        },
                        {
                            id: 42,
                            text: '参加学生艺术团队'
                        }
                    ]
                },
                {
                    id: 5,
                    text: '社会实践管理',
                    children: [
                        {
                            id: 51,
                            text: '社会实践参与项目'
                        },
                        {
                            id: 52,
                            text: '科技创新、研究性学习成果'
                        },
                        {
                            id: 53,
                            text: '创造发明成果'
                        }
                    ]
                },
                {
                    id: 6,
                    text: '典型案例材料',
                    children: [
                        {
                            id: 61,
                            text: '典型案例材料'
                        }
                    ]
                }
            ],
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'text'
                }
            ]
        }, cfg)]);
    }
});